### ISSUE TITLE
Create/update secrets from file

### ISSUE THREAD

**Issue by tsmethurst** [dcos-labs/ansible-dcos-module#6]
Hiya,
I wanted to add a couple functions to `dcos_secret.py` that allow for the creation of secrets from files (following [this documentation](https://docs.d2iq.com/mesosphere/dcos/1.13/security/ent/secrets/create-secrets/#creating-secrets-from-a-file-via-the-dcos-enterprise-cli)). I made the changes locally and wanted to push them to a branch so I could make a PR, but I don't have permissions to do so. Can I get permissions to make a branch or something, so you can review my changes and possibly (hopefully) incorporate them into master?

Thanks!
Tobi

**Comment by tsmethurst** [comment]
Update: forked it and created a PR here https://github.com/dcos-labs/ansible-dcos-module/pull/7

**Comment by jrx** [comment]
PR #7 was merged. Thanks again!
